### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by adityamukho** [arangodb/foxx-apps#10]
Hello,

I'd like to raise a PR to add my Foxx microservice to the apps list, but looks like this repository hasn't seen much activity lately. I can see an open PR standing since Dec 2017.

Is this still the right place to raise such PRs, or is there a separate _Foxx Apps Marketplace_ somewhere, or is this no longer a viable route for distributing user-created services?

**Comment by pluma** [comment]
The Foxx service "store" hasn't seen much love lately as most of the development effort went into ArangoDB itself, but this repo is still the right place to submit your service if you want it to appear in ArangoDB for other users.
