### ISSUE TITLE
Discrepancy in records fetched between DB UI and Foxx _query method

### ISSUE THREAD

**Issue by AnushaVasanth-tech** [arangodb/foxx-apps#13]
Hello,
We are facing strange issue on foxx Javascript method db._query. A specific query with multiple AND and ternary operators gives different set of records in FOXX engine when compared the result retrieved via DB UI.
Difference in following 2 params:
Total count ( from DB UI, # of total records: 9646, with foxx' _query method only 2046 records have been fetched). There is no limit set in query.
when option "fullCount" is set on method "_query", the result contains additional flag "fullCount":9464, (matches the count from DB UI)
Following readings are noted for response:
```
"_countTotal": 2046,
    "_countQuery": 2046,
    "_skip": 0,
    "_limit": null,
    "_cached": false,
    "_extra": {
        "stats": {
            "writesExecuted": 0,
            "writesIgnored": 0,
            "scannedFull": 0,
            "scannedIndex": 10268,
            "filtered": 280921,
            "httpRequests": 0,
"fullCount":9464,
            "executionTime": 2.312915200018324,
            "peakMemoryUsage": 77466514
        },
        "warnings": []
    },
    "_current": 0,
    "_stop": 2046
```
The result of query is array of objects. When result from FOXX is examined, it was noted that, "null" had been replaced for empty array ( [] ) on random basis for few of nodes.
Version details:
Arango DB: 3.7.15, rocksDB

Note: The query worked fine on Arango v3.2, 3.3 and 3.6

Could you advise the possible root cause for the discrepancy. If there is any limit on any parameter on foxx engine is set by default OR if there is any configurable parameter available?

Please revert for any more details on description of issue.
Regards,
Anusha

**Comment by dothebart** [comment]
Hi,
can you please open this issue on the main arangodb repo?
Please also add an example data set reproducing the issue. 
Maybe you can reproduce the incident with just a `RETURN` statement with a static object?
How did you upgrade? upgrade in place? or dump & restore + switch from mmfiles -> rocksdb?

**Comment by AnushaVasanth-tech** [comment]
Hi,
Thank you for responding, created issue on main repo ( https://github.com/arangodb/arangodb/issues/15107 ) with all the details requested.

**Comment by dothebart** [comment]
ok, will close this one, so that it can be continued over there, thanks.
