### ISSUE TITLE
Confusion about using collections in resolve function

### ISSUE THREAD

**Issue by outre99** [arangodb/foxx-apps#3]
Hello,
i've been working through the graphql example and can't figure out how actual collections are linked to the type definitions resolve functions.
In the example it says: 
"// In the original graphql-js test fixtures episodes
// are defined using a GraphQL ENUM type. Because we're
// in a database, it makes more sense to define them
// as an object type backed by a collection.
"

and the resolve functions is:

`        resolve(episode) {
          // The objects exposed by GraphQL have an "id"
          // field which corresponds to ArangoDB's "_key"
          // property. This mapping isn't strictly necessary
          // but hides the implementation of the data
          // source to make it more consistent with other
          // GraphQL APIs.
          return episode._key;
`

while the collection reference is set by:

`const episodes = applicationContext.collection('episodes');`

so how is 'episode' in resolve function connected to 'episodes' collection reference?

Thanks in advance.

**Comment by pluma** [comment]
Continued at https://github.com/arangodb-foxx/demo-graphql/issues/1
